# Site settings
title: SP 800-157r1 Guidelines for Derived Personal Identity Verification (PIV) Credentials
description: NIST Special Publication 800-157r1 Guidelines for Derived Personal Identity Verification (PIV) Credentials
baseurl: "/800-157r1" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- BUILD.md
- "*.yml"
- "*/images/*.pdf"

# GitHub information will uncomment ones names are finalized and NIST GitHub Pages resources have been allocated
org_name: usnistgov
repo_name: 800-157r1

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
  collection: false
- text: SP 800-157r1
  url: /introduction/
  collection: sp800-157
  anchor: s-1
  
  
collections:
  sp800-157:
    output: true

relative_links:
  enabled:     true
  collections: true

#Uncomment when we go live 
host: 0.0.0.0

include:
- _stylesheets
- _javascript

# Custom site configuration
lang: en

abstract:
  sp800-157:
    subject: "This recommendation provides technical guidelines for the implementation of standards-based, secure, reliable credentials that are issued by federal departments and agencies to individuals who possess and prove control of their valid PIV Card. These credentials can be either public key infrastructure (PKI)-based like the PIV Card or non PKI-based but verified by the individual's home agency. The scope of this document includes requirements for the initial issuance and maintenance of these credentials, certificate policies as applicable, cryptographic specifications, technical specifications for permitted authenticator types, and the command interfaces for removable implementations of such PKI-based credentials."
    keywords: 'authentication; credentials; derived PIV credentials; electronic authentication; electronic credentials; mobile devices; personal identity verification; PIV'
